### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by amovah**
use ES6 classes, improve encryption, add a couple features, change API a little.

Fix this [issue](https://github.com/BosNaufal/secure-local-storage/pull/4#issuecomment-203972132) in chrome. thank you @BosNaufal

### CODE REVIEW

**Comment by BosNaufal** [comment]
Hey @amovah, Would you like to make more little perfection in local storage index? because the password looks naked [here](http://ctrlv.in/732734)

**Comment by amovah** [comment]
Sorry, I forgot to fix that. @BosNaufal thank you. try it now.

**Comment by BosNaufal** [comment]
Wow! you did it @amovah ! It's so pretty cool now! :smile:

**Comment by BosNaufal** [comment]
Hey @amovah, I saw the security hole in your script. the class property is exposed. It means is easy to find out the password. check it out~

[Exposed Password](http://ctrlv.in/732940)

But I've just worked with your branch and edited some line. You can check it in my master branch~

[Unexpose The Class Property](http://ctrlv.in/732941)

You can try it live [here](https://rawgit.com/bosnaufal/secure-local-storage/master/index.html). Open your console and explore the "storage" variable.

The Problem is... I can't make some UMD js for it, but you did. would you like help me?

**Comment by BosNaufal** [comment]
Hey @amovah, There's somebody told me that client side security is just a dream since it's declared on the client side which is easy to see the code even the password via chrome debugs tools. 

But it still has a chance if it can hide the method in the browser (only) like crypto-js did.

[this is my question](http://stackoverflow.com/questions/36368955/how-crypto-js-hide-the-class-method).

**Comment by amovah** [comment]
Hey @BosNaufal, It's very good now. I like your idea for hiding method and password from SecureStorage class.

hiding method is impossible, as I know.

**Comment by BosNaufal** [comment]
@amovah How do you think if we separate the "set password" method?

**Comment by amovah** [comment]
I don't know. I think "password" is good enough, but if think you think it's not good, so It's not good.

**Pull request closed without merging**
