### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by amovah**
use ES6 classes, improve encryption, add a couple features, change API a little

### CODE REVIEW

**Comment by BosNaufal** [comment]
Great work @amovah! :smile: 
But the Example seems not working correctly~

**Comment by amovah** [comment]
which example doesn't work? readme example or html example?

**Comment by BosNaufal** [comment]
I tried to access readme example and got error log.
got error

**Comment by amovah** [comment]
which one did you use?
You must use secure-local-storage.js that it is in build directory [secure-local-storage](https://github.com/amovah/secure-local-storage/blob/master/build/secure-local-storage.js).

I've just checked it, and it does work.

**Comment by BosNaufal** [comment]
I just try this [link](https://rawgit.com/amovah/secure-local-storage/master/index.html) from your branch.
Would you like to give me the working example link?

**Comment by amovah** [comment]
and It's my screenshot on that link. It does work. Can you try with Firefox?
screen shot 2016-03-31 at 9 49 38 pm

**Comment by BosNaufal** [comment]
Hi @amovah, in firefox working well. but in chrome it doesn't work. But it might be work if you change little part of the script in the index.html from "let" to "var". You've done great!

**Comment by amovah** [comment]
Yes. it's my fault. I'll fix it and make a new PR. thank you.

**Pull request merged**
